"""add ai_insight table

Revision ID: 56b9dc032502
Revises: 1055ee8ebb70
Create Date: 2026-03-05 15:20:08.942528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '56b9dc032502'
down_revision: Union[str, Sequence[str], None] = '1055ee8ebb70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('insight_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'start_month', 'end_month')
    )
    op.create_index(op.f('ix_ai_insight_end_month'), 'ai_insight', ['end_month'], unique=False)
    op.create_index(op.f('ix_ai_insight_start_month'), 'ai_insight', ['start_month'], unique=False)
    op.create_index(op.f('ix_ai_insight_user_id'), 'ai_insight', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_insight_user_id'), table_name='ai_insight')
    op.drop_index(op.f('ix_ai_insight_start_month'), table_name='ai_insight')
    op.drop_index(op.f('ix_ai_insight_end_month'), table_name='ai_insight')
    op.drop_table('ai_insight')
    # ### end Alembic commands ###
