"""added budget to category

Revision ID: 821ea7729ed6
Revises: d52a8fb81dd5
Create Date: 2026-02-13 22:12:28.201421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821ea7729ed6'
down_revision: Union[str, Sequence[str], None] = 'd52a8fb81dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('budget', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'budget')
    # ### end Alembic commands ###
