"""update user

Revision ID: cc966aed8a1c
Revises: 39fa6c24da04
Create Date: 2026-02-15 21:09:24.604786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cc966aed8a1c'
down_revision: Union[str, Sequence[str], None] = '39fa6c24da04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column(
            'provider',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='local',
        ),
    )
    op.add_column('user', sa.Column('google_sub', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column(
        'user',
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
    )
    op.add_column(
        'user',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column('user', 'provider', server_default=None)
    op.alter_column('user', 'created_at', server_default=None)
    op.alter_column('user', 'is_active', server_default=None)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_google_sub'), 'user', ['google_sub'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_google_sub'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'google_sub')
    op.drop_column('user', 'provider')
    # ### end Alembic commands ###
