"""add foreign keys

Revision ID: ef6849dcdfb6
Revises: fa3f14d0f5f5
Create Date: 2026-01-27 21:08:59.051264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6849dcdfb6'
down_revision: Union[str, Sequence[str], None] = 'fa3f14d0f5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_user_id'), table_name='category')
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_income_user_id'), table_name='income')
    op.create_foreign_key(None, 'income', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_transaction_category_id'), table_name='transaction')
    op.create_foreign_key(None, 'transaction', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_index(op.f('ix_transaction_category_id'), 'transaction', ['category_id'], unique=False)
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.create_index(op.f('ix_income_user_id'), 'income', ['user_id'], unique=False)
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_index(op.f('ix_category_user_id'), 'category', ['user_id'], unique=False)
    # ### end Alembic commands ###
