"""add month to category

Revision ID: f291d74b5c9f
Revises: 46120e16fe28
Create Date: 2026-03-05 09:36:13.360503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f291d74b5c9f'
down_revision: Union[str, Sequence[str], None] = '46120e16fe28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('month', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_category_month'), 'category', ['month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_month'), table_name='category')
    op.drop_column('category', 'month')
    # ### end Alembic commands ###
